#!/bin/bash
###
### FootPrint Added, see Prefixed-Var ZSEAddFootPrint from ZenityShellEval
###

###File:/var/cache/Fnct.D/ZenityShellEval/023102e0-1833-11e3-98a2-001b3875b29c
###UUID-TIME-MARKER:ecdcc62a-9a3b-11e6-8b1d-3de3cec4dffe
###Date: 20161024-18:48:04,1477349284
###Sha1Sum: e09c41161098da4414c58792f7d1aed060b370b1
###Size:799
###NbLine: 23
###NbWord: 75


unset __GetVarReferenceCompWord ;
function __GetVarReferenceCompWord( )
{
  local StrFuncVar="${__call_locality[1]}" ;
  local StrPVarStart=$( GetStdPrefixName ${__call_locality[1]} ) ; 
  local template="unset ___CALL_LOCALITY__  ; 
  function ___CALL_LOCALITY__() 
  { 
   local PrefixedVar PrefixedItem ;  
   COMPREPLY=( \$( compgen -W __GUILL__\$( __CALL_LOCALITY__ --list ) __GUILL__ ) ) ; 
   if ( \${COMP_WORDS[1]} = +(__PVAR__) ) ; then 
    PrefixedVar=__GUILL__ \${COMP_WORDS[\$(( COMP_CWORD-1 ))]} \${COMP_WORDS}__GUILL__ ; 
    fi ; 
  } ;  
  complete -F ___CALL_LOCALITY__ __CALL_LOCALITY__ ; " ;
  template=${template//__CALL_LOCALITY__/${StrFuncVar}};
  template=${template//__PVAR__/${StrPVarStart}} ;
  template=${template//__GUILL__/\"} ; 
  echo -ne "eval ${template}" ;  
}
