#!/bin/bash
###
### FootPrint Added, see Prefixed-Var ZSEAddFootPrint from ZenityShellEval
###

###File:/home/maxiste/github/Fnct.D/0f86b448-72f4-11e6-8b1d-001e4c8856d6
###UUID-TIME-MARKER:24a64a42-ee90-11e6-8b1d-001e4c8856d6
###Date: 20170209-01:22:39,1486621359
###Sha1Sum: 2c4f86e335a630bcc4e260a2b251a0525801b3d5
###Size:13270
###NbLine: 337
###NbWord: 1249


unset GetDateReportCreation; 
function GetDateReportCreation()
{
 local ArrayArg=( $* ) ;
 local __call_locality=( GDRC GetDateReportCreation ) ;
 local Arg0=${ArrayArg[0]} ; 
 local StrDateFormat=${GDRCDateFormat:="%Y%m%d_%H%M%S"} ; 
 local StrDateApps=${GDRCDateApps:=GetOtherDate} ;
 local StrVarListTransfert="StrDateFormat,StrDateApps" ;
 local StrSwitchMessages="${StrSwitchesShow}${StrStartSwitches}\n${StrGetMsgSwitches}\n${StrListMsgSwitches}\n${StrCompWordMsgSwitches}\n" ;
 
 function __main_StartServices()
 {
  GODShowVersion=False GODFormat=${StrDateFormat} ${StrDateApps} ; 
 }
 
 
 if [ "${Arg0:=--startservices}" == "--help"	] ; then 
  GetVarReference ${__call_locality[1]} ; 
  echo -ne "${StrSwitchMessages}" > /dev/stderr ; 
 elif [ "${Arg0:=--startservices}" == "--get" ] ; then 
  eval """local ArgGet=\${${ArrayArg[1]}}""" ; 
  echo -ne """${ArgGet}\n""" ;
 elif [ "${Arg0:=--startservices}" == "--list" ] ; then 
  eval $( __GetVarReferenceList ) ;
 elif [ "${Arg0:=--startservices}" == "--compword" ] ; then 
  eval $( __GetVarReferenceCompWord ) ;
 elif [ "${Arg0:=--startservices}" == "--startservices" ] ; then 
  eval $( eval VTVIsArrayStyleInsert=True      \
          VTVValueEntry=${StrVarListTransfert} \
          VTVIsValueReAssign=True              \
          VTVIsValueToConvert=False            \
          VTVIsArrayStyleInsert=True           \
          ValueToVariable ) __main_StartServices
 fi
}


 
 
### ##########################################################################
### #                                  MdCd
### ##########################################################################

unset GetMemContent GetMemHeader ShaSum1 GetCol1 MdCd ;
unset Verbosis ; 
function MdCd()
{ 
 function Verbosis()
 {
  local -a ArrayArg=( $* ) ; 
  local -a __call_locality=( Verbosis Verb );
  local StrMsg=${VerbMsg:=__TEXT__} ; 
  local StrDevOut=${VerbDev:=/dev/stderr} ; 
  local IsVerboseState=${VerbState:=False} ;
  local StrVerboseHeader=${VerbHeader:=VERBOSE} ;
  local IsDisplayFormatted=${VerbFormated:=True} ;
  if [ "${IsVerboseState:=False}" == "True" ] ; then 
   if [ "${IsDisplayFormatted:=True}" == "True" ] ; then 
     echo -ne "${StrVerboseHeader}:[ ${StrMsg} ]\n" > ${StrDevOut} ;
   else
     echo -ne "${StrMsg}\n" > ${StrDevOut} ;
   fi 
  fi
 } 
 ### Model :VerbMsg=MSG VerbHeader=DEBUG VerbFormated=True VerbState=${BoolDisplayDebug} VerbDev=/dev/stderr  Verbosis
 function GetCol1()
 {
  local -a __call_locality=( GC1 GetCol1 ) ;
  local -a ArrayArg=( $* ) ; 
  local Arg0=${ArrayArg[0]} ;
  local StrApps=${GC1Apps:=/usr/bin/cut} ;
  local StrAppsOpt=${GC1AppsOpt:="-d ' ' -f 1"} ;
  eval "${StrApps} ${StrAppsOpt}" ;
 }
	
 function ShaSum1()
 {
  local -a __call_locality=( SS1 ShaSum1 ) ;
  local -a ArrayArg=( $* ) ; 
  local Arg0=${ArrayArg[0]} ;
  local StrApps=${SS1Apps:=/usr/bin/sha1sum} ;
  ${StrApps} ; 
 }	
	
 function GetMemHeader()
 {
  local -a __call_locality=( GMH GetMemHeader ) ;
  local -a ArrayArg=( $* ) ; 
  local Arg0=${ArrayArg[0]} ;
  echo "${ArrayMdCd[@]}" | ShaSum1 | GetCol1
 }
	
 function GetMemContent()
 {
  local -a __call_locality=( GMC GetMemContent )
  local -a ArrayArg=( $* ) ; 
  local Arg0=${ArrayArg[0]} ; 
  echo "${ArrayMdCd[@]}" ; 
 }

 local -a ArrayArg=( $* ) ;
 local -a __call_locality=( MC MdCd ) ;
 local Arg0="${ArrayArg[0]}" ; 
 local StrAppsExpandModel=${MCAppsExpandModel:=/bin/tar} ;
 local StrAppsCall=${MCAppsExpandCall:=__APPS__ __OPT__} ;
 local StrAppsExpandOpt=${MCAppsExpandOpt:=-x -j -f __FILE__ -C __PATH__} ;
 local StrMkDirApps=${MCMKDIRApps:=/bin/mkdir} ; 
 local StrLocationTemplate=${MCTemplatePath:=${StrBasePath}} ; 
 local StrPathModelTemplate=${MCTemplatePathModel:=NewPathModel.tar.bz2}
 local StrFileModel=${StrLocationTemplate}/${StrPathModelTemplate} ; 
 local IntGetContentId=${MCContentId:=2} ; 
 local StrDevOut=${MCDevOut:=/dev/stderr} ;
 local StrTagCmdParser=${MCCmdTagParserRules:=StrAppsExpandModel:__APPS__,StrAppsExpandOpt:__OPT__,StrFileModel:__FILE__,StrPathLoc:__PATH__}; 
 local StrFileList=${MCListFile:=None} ; 
 local -a ArrayFile=( ${StrFileList//,/ } ) ; 
 local IntFile=$(( ${#ArrayFile[@]}-1 ))  ; 
 local StrPathCurPtr=${MCCurGetPath:=None} ; 
 local StrDevOut=${MCDevOut:=/dev/stderr} ;
 local StrStoreTpl="__DATE__:__PATH__:__UTLM__:__RES__" ;
 local BoolDisplayDebug=${MCDisplayDebug:=False} ; 
 local StrVTVRegistry=${MCVTVReg:='VTVIsQuotedValue=True VTVIsValueReAssign=True VTVIsValueToConvert=False VTVIsArrayStyleInsert=True VTVIsWhiteList=True VTVIsArrayStyleInsert=True'} ; 
 local StrVarListTransfert="BoolDisplayDebug,StrStoreTpl,StrFileList,StrAppsCall,StrMkDirApps,StrTagCmdParser,GCID,GHID,IntFile,StrFileStoreInfo,StrDate,StrPathLoc,UserTypeLocationModel,GetHeaderId,IntGetContentId,StrAppsExpandModel,StrAppsExpandOpt,StrFileModel,StrVTVRegistry" ;
 local StrSwitchMessages="${StrSwitchesShow}${StrStartSwitches}\n${StrGetMsgSwitches}\n${StrListMsgSwitches}\n${StrCompWordMsgSwitches}\n" ;
 local ArrayMsg=( ) ;
 ArrayMsg[0]="CMD: __CMD__, PATH: __PATH__  " ;
 ArrayMsg[1]="StrFileStoreInfo : __FSI__" ; 
 ArrayMsg[2]="StrFileStoreLock : __FSL__" ; 
 ArrayMsg[3]="UserTypeLocationModel : __UTLM__" ; 
 ArrayMsg[4]="Processing Creation of __PATH__" ; 

 function __main_StartServices()
 {
  local -a __call_locality=( Main __main_StartServices ) ;
  local -a ArrayArg=( $* ) ;
  local Arg0=${ArrayArg[0]} ;  
  local -a ArrayDebugTag ;
  local -a ArrayMdCd ; 
  local StrMsg ;
  local StrPathLoc="" ; 

  ArrayDebugTag[0]="${__call_locality[1]}-DEBUG" ; 
  ArrayDebugTag[1]="${__call_locality[1]}-PATH" ; 
  ArrayDebugTag[2]="${__call_locality[1]}-CMDLINE" ; 
  ArrayDebugTag[3]="${__call_locality[1]}-TAGPARSER" ; 

  ### Verbose Block
  StrMsg=$( MdCd --get ArrayMsg[1] ) ; 
  StrMsg=${StrMsg//__FSI__/${StrFileStoreInfo}}
  VerbMsg="${StrMsg}"              \
  VerbHeader="${ArrayDebugTag[0]}" \
  VerbState=${BoolDisplayDebug}    \
  VerbFormated=True                \
  VerbDev=${MCDevOut} Verbosis ;
  
  ### Verbose Block
  StrMsg=$( MdCd --get ArrayMsg[2] ) ; 
  StrMsg=${StrMsg//__FSL__/${StrFileStoreLock}}
  VerbMsg="${StrMsg}"              \
  VerbHeader="${ArrayDebugTag[0]}" \
  VerbState=${BoolDisplayDebug}    \
  VerbFormated=True                \
  VerbDev=${MCDevOut} Verbosis ;

  local UserTypeLocationModel="${StrLocationTemplate}/${StrPathModelTemplate}" ;
  
  ### Verbose Block
  StrMsg=$( MdCd --get ArrayMsg[3] ) ; 
  StrMsg=${StrMsg//__UTLM__/${UserTypeLocationModel}}
  VerbMsg="${StrMsg}"              \
  VerbHeader="${ArrayDebugTag[0]}" \
  VerbState=${BoolDisplayDebug}    \
  VerbFormated=True                \
  VerbDev=${MCDevOut} Verbosis ;
   
    
  local currentSHA=$( GBLDAction=GetHeader GBLDFileStoreInfo=${StrFileStoreInfo} IntGHId=1 GetterByLineData ) ;
  local StrContent=$( GBLDAction=GetContent GBLDFileStoreInfo=${StrFileStoreInfo} IntGCId=2 GetterByLineData ) ; 
  local ErrContent=$? ; 
  if [ ${ErrContent:=-1} -eq 0 ] ; then 
   ### Replacing declare by a local declare -a ArrayMdCd=( ${StrContent} ${ArrayMdCd[@]} );
   ArrayMdCd=( ${StrContent} ${ArrayMdCd[@]} );
  else
   ### replacing by a local var declare -a ArrayMdCd=( ${ArrayMdCd[@]} );
   ArrayMdCd=( ${ArrayMdCd[@]} );
  fi 
  

  ### The Index of number of intem inside the array are initialized inside the Top
  ### Function MdCd under name IntFile and travel thru ValueToVAriable here.  
  local PathFromGetter="" ; 
  local StrStoreStream="" ;
  local StrDate=$( GetDateReportCreation ) ;
  local ArrayMdCdTag="" ;
  local CmdLine="" ; 
  local StrPathTpl=$( MdCd --get ArrayMsg[4] ) ;
  for (( intx=0 ; intx <= ${IntFile} ; intx++ )) ; do 
   StrPathLoc=$( MdCd --get ArrayFile[${intx}] ) ; 
   StrMsg=${StrPathTpl} ; 

   ### Verbose Block
   StrMsg=${StrMsg//__PATH__/${StrPathLoc}} ;
   VerbMsg="${StrMsg}"             \
   VerbHeader="${ArrayDebugTag[1]}" \
   VerbFormated=True               \
   VerbState=${BoolDisplayDebug}   \
   VerbDev=${MCDevOut}  Verbosis ;
   
   ### PathFromGetter=$( MCCurGetPath="${StrPathLoc}" MdCd --get MCCurGetPath ) ; 
   if [ ! -d "${StrPathLoc}"  ] ; then 
    StrCmdLine="""${StrMkDirApps} -p ${StrPathLoc}""" ; 
    
    ### Verbose Block
    VerbMsg="${StrCmdLine}"          \
    VerbHeader="${ArrayDebugTag[2]}" \
    VerbState=${BoolDisplayDebug}    \
    VerbFormated=True                \
    VerbDev=${MCDevOut} Verbosis ;
    $( eval "${StrCmdLine}" ) ;
   fi 
   ### Notice : 917a3c2a-e331-11e5-98a2-001e4c8856d6 
   ### Note : Problems in tar command fixed. Tar command works in different way
   ### unless somes libs where updated. 
   ######
   # cd ${StrPathLoc} ###---> No longer needed, tar problems ; Somes accounts did not 
   # drop de model-default file inside the path. 
   ######
   
   ### Ask for a copy or recall it from $( MdCd --get StrAppsCall )  ?
   #local ArrayMdCdTag=( ${StrTagCmdParser//,/ } ) ; 
   local StrCmdLineTar="${StrAppsCall}" ;  

   eval StrTagCmd=$( eval \
     TPDisplayParserNotice=${BoolDisplayDebug} \
     TPDisplayDebug=${BoolDisplayDebug}        \
     TPArrayName=ArrayMdCdTag                  \
     TPVarNameParsed=StrCmdLineTar             \
     TPListTag="${StrTagCmdParser}"            \
     TagParser  ) ; 

   ### Verbose Block
   VerbMsg="${StrTagCmd}"           \
   VerbHeader="${ArrayDebugTag[2]}" \
   VerbFormated=True                \
   VerbState=${BoolDisplayDebug}    \
   VerbDev=${MCDevOut}  Verbosis ; 
   
   eval $( eval """${StrTagCmd}""" ) ; 
   
   ### Verbose Block
   VerbMsg="${StrCmdLineTar}"       \
   VerbHeader="${ArrayDebugTag[3]}" \
   VerbFormated=True                \
   VerbState=${BoolDisplayDebug}    \
   VerbDev=${MCDevOut}  Verbosis ; 
   
   #for StrPairTagVal in ${ArrayMdCdTag[@]} ; do
    ### In String ${.../%Pattern} will remove only the end
    ### In String ${.../#Pattern} will remove only the beginning
    #StrPairLeft=${StrPairTagVal/%:[A-Za-z0-9]*/}
    #StrPairRight=${StrPairTagVal/#__[A-Za-z0-9]*__:/} ;
    #eval "CmdLine=${CmdLine//\${${StrPairLeft}}/${StrPairRight}}" ; 
    ### Notice : e395ecfc-6d8d-11e6-8b1d-001e4c8856d6
    ### Note : Storing Value inside a volatile Getter. 
    ### A volatile getter is a Variable with value=None until you query it inside a Parsing Model
    ### from Main Application Header and stipulate a Law like __PATH__:MCCurGetPath
    ### This one will return None if MdCd --get MCCurGetPath( not StrPathCurPtr ) is called. 
    ### Therefore developping a solid and straight-forward model of Loop-sequence 
    ### with stipping Left AND Right value and implying the Getter of this function 
    ### to repond by a value nominated inside Pre-definied value, path are stored 
    ### inside $* and are converted to be re-marshalled Here we are treating only 
    ### one of the path which involving to make a if statement and and to reduce 
    ### the sequence. While it's adding extra code, it skipping line simply parsing 
    ### the path we already have inside a Getter that ultimateli send us the 
    ### path when it's the time to ask about it. 

   #done
   ### Verbose Block
   VerbMsg="${StrCmdLineTar}"       \
   VerbHeader="${ArrayDebugTag[2]}" \
   VerbFormated=True                \
   VerbState=${BoolDisplayDebug}    \
   VerbDev=${MCDevOut}  Verbosis ;

   StrMsg=$( MdCd --get ArrayMsg[0] ) ; 
   StrMsg="${StrMsg//__CMD__/}" ; 
   StrMsg="${StrMsg//__PATH__/}" ; 
   VerbMsg="${StrMsg}"              \
   VerbHeader="${ArrayDebugTag[0]}" \
   VerbDev=${MCDevOut}              \
   VerbState=${BoolDisplayDebug} Verbosis ; 
   #echo -ne "Cmd:[ tar xvjfC ${UserTypeLocationModel} ${StrPathLoc} ]\n" > ${MCDevOut} ; 
   #StrAppsExpandModel,
   #StrAppsExpandOpt
   if [ -f ${UserTypeLocationModel} ] ; then 
    eval $( eval """${StrCmdLineTar}""" ) 2> /dev/null ;
    resultTar=$? ; 
   fi 
   local StrResult="No" ; 
   local StrStoreStream="${StrStoreTpl}" ; 
   if [ ${resultTar:=1} -eq 0 ] ; then 
    StrResult="Yes" ; 
   fi
   StrStoreStream="${StrStoreStream//__DATE__/${StrDate}}" ; 
   StrStoreStream="${StrStoreStream//__PATH__/${StrPathLoc}}" ; 
   StrStoreStream="${StrStoreStream//__UTLM__/${UserTypeLocationModel}}" ; 
   StrStoreStream="${StrStoreStream//__RES__/${StrResult}}" ; 

   ArrayMdCd[${#ArrayMdCd[@]}]="${StrStoreStream}" ;  
   #echo "cd ${StrPathLoc} ;" ;
  done 
  ### GetMemHeader > ${StrFileStoreInfo} ; 
  echo "${ArrayMdCd[@]}" | ShaSum1 | GetCol1 > ${StrFileStoreInfo} ; 
  ###GetMemContent >> ${StrFileStoreInfo} ; 
  echo "${ArrayMdCd[@]}" >> ${StrFileStoreInfo} ;
 } 
 
 if [ "${Arg0:=--startservices}" == "--help"	] ; then 
  GetVarReference ${__call_locality[1]} ; 
  echo -ne "${StrSwitchMessages}" > /dev/stderr ; 
 elif [ "${Arg0:=--startservices}" == "--get" ] ; then 
  eval """local ArgGet=\${${ArrayArg[1]}}""" ; 
  echo -ne """${ArgGet}\n""" ;
 elif [ "${Arg0:=--startservices}" == "--list" ] ; then 
  eval $( __GetVarReferenceList ) ;
 elif [ "${Arg0:=--startservices}" == "--compword" ] ; then 
  eval $( __GetVarReferenceCompWord ) ;
 elif [ "${Arg0:=--startservices}" == "--startservices" ] ; then 
  $( eval ${StrVTVRegistry}                \
     VTVValueEntry=${StrVarListTransfert}  \
     VTVWhiteListTransfert=GCID,GHID       \
     ValueToVariable ) __main_StartServices ; 
 fi
}
