#!/bin/bash
###
### FootPrint Added, see Prefixed-Var ZSEAddFootPrint from ZenityShellEval
###

###File:/var/cache/Fnct.D/ZenityShellEval/69968204-0cf6-11e3-99bc-001b3875b29c
###UUID-TIME-MARKER:50731f20-9a3e-11e6-8b1d-001e4c8856d6
###Date: 20161024-19:05:11,1477350311
###Sha1Sum: ed6a4111e80df6a542995cd92ae76b213bff6e37
###Size:1550
###NbLine: 44
###NbWord: 154



function GetStdPrefixName()
{
  local ArrayArg=( $* ) ; 
  local __call_locality=( GSPN GetStdPrefixName  ) ; 
  local StrPrefixEntry=${GSPNArg0:=None} ; 
  local Arg0=${ArrayArg[0]} ; 
  
  local StrSedDefFilter=${GSPNSedFilter:=s/[a-z\)\(\_\-]//g} ; 
  local StrSwitchMessages="Following switch are available:\n\n\t--startservices\tStart the application normally.\n\t--get\t\tReturn value of Internal Variable.\n\t--list\t\tList all Internal Pre-fixed Variable available to query or get.\n\n" ;
		 
 function __main_StartServices()
 {
   local __call_locality=( Main __main_StartServices ) ;
   local ArrayArg=( $* ) ; 
   local Arg0=${ArrayArg[0]};
   if [ ${StrPrefixEntry:=None} == "None" ] ; then 
     echo -ne "${Arg0}\n" | eval "sed '${StrSedDefFilter}'" ;
   else
     echo -ne "${StrPrefixEntry:=None}\n" | eval "sed '${StrSedDefFilter}'" ;
   fi 
 }
 
  if [ "${Arg0:=--startservices}" == "--help"	] ; then 
   GetVarReference ${__call_locality[1]} ; 
   echo -ne "${StrSwitchMessages}" > /dev/stderr ; 
  elif [ "${Arg0:=--startservices}" == "--get" ] ; then 
   eval """local ArgGet=\${${ArrayArg[1]}}""" ; 
   echo -ne """${ArgGet}\n""" ;
  elif [ "${Arg0:=--startservices}" == "--list" ] ; then 
   eval $( __GetVarReferenceList ) ;
  elif [ "${Arg0:=--startservices}" == "--startservices" ] ; then 
   StrSedDefFilter=${StrSedDefFilter}    \
   StrPrefixEntry=${StrPrefixEntry}         \ 
   __main_StartServices
  else
   StrSedDefFilter=${StrSedDefFilter}    \
   __main_StartServices                          ${Arg0}; 
 fi

}
