#!/bin/bash
###
### FootPrint Added, see Prefixed-Var ZSEAddFootPrint from ZenityShellEval
###

###File:/var/cache/Fnct.D/ZenityShellEval/6e063cbc-0ce2-11e3-8879-001b3875b29c
###UUID-TIME-MARKER:bc798d88-9a31-11e6-8b1d-001e4c8856d6
###Date: 20161024-17:35:08,1477344908
###Sha1Sum: 61e411af5827f0c6fca4275d0d9d6576c0bdae74
###Size:4386
###NbLine: 104
###NbWord: 308




function AnsiCodeTest()
{
  local ArrayArg=( $* ) ; 
  local __call_locality=( ACT AnsiCodeTest  ) ; 
  local Arg0=${ArrayArg[0]} ; 
  local IntStartRange=${ACTStartRange:=10} ;
  local IntEndRange=${ACTEndRange:=50} ;
  local StrAnsiResetCode=${ACTResetCode:=033[00m} ; 
  local StrStringSample=${ACTStringSample:=[TEST]} ;
  local StrErrDev=${ACTErrDev:=/dev/stderr} ; 
  local BoolUniqueVal=${ACTEIsUniqueValue:=False} ; 
  local BoolDisplayInfo=${ACTEIsDisplayInfo:=True} ; 
  local IntValue=${ACTEValue:=36} ; 
  local StrVarList="BoolUniqueVal,BoolDisplayInfo,IntValue,IntStartRange,IntEndRange,StrAnsiResetCode,StrStringSample,StrErrDev" ; 
 
 function LoopDisplay()
 {
   local __call_locality=( LD LoopDisplay ) ;
   local ArrayArg=( $* ) ; 
   local Arg0=${ArrayArg[0]} ;
   for (( intx=${IntStartRange} ; intx <= ${IntEndRange} ; intx++ )) ; do 
    if [ "${BoolDisplayInfo:=True}" == "True" ] ; then
     StrLineDisplay=${StrDisplayTpl} ;
    else
     StrLineDisplay=${StrDisplayText};
    fi 
    
    StrLineDisplay=${StrLineDisplay//__CODE_DISPLAY__/${StrAnsiCodeDisplay}} ; 
    StrLineDisplay=${StrLineDisplay//__TEXT__/${StrStringSample}} ; 
    StrLineDisplay=${StrLineDisplay//__RESET__/${StrAnsiResetCode}} ; 
    StrLineDisplay=${StrLineDisplay//__ANSI_CODE__/${StrAnsiCode}} ;
    StrLineDisplay=${StrLineDisplay//__COUNT__/${intx}} ;
    echo -ne "${StrLineDisplay}\n" > ${StrErrDev} ; 
   done   
  
  
 }
 function __main_StartServices()
 {
   local __call_locality=( Main __main_StartServices ) ;
   local ArrayArg=( $* ) ; 
   local Arg0=${ArrayArg[0]} ;
   local StrDisplayText="\\__RESET____ANSI_CODE____TEXT__\\__RESET__"
   local StrDisplayTpl="\\__RESET__Color no.__COUNT__, Ansi Code '__CODE_DISPLAY__' : __ANSI_CODE____TEXT__\\__RESET__" ; 
   local StrAnsiCode="\033[01;__COUNT__m" ;
   local StrAnsiCodeDisplay="""\\\033[01;__COUNT__m""" ;
   if [ "${BoolUniqueVal:=False}" == "True" ] ; then 
     if [ "${BoolDisplayInfo:=True}" == "True" ] ; then 
      StrLineDisplay=${StrDisplayTpl} ; 
      StrLineDisplay=${StrLineDisplay//__CODE_DISPLAY__/${StrAnsiCodeDisplay}} ; 
      StrLineDisplay=${StrLineDisplay//__TEXT__/${StrStringSample}} ; 
      StrLineDisplay=${StrLineDisplay//__RESET__/${StrAnsiResetCode}} ; 
      StrLineDisplay=${StrLineDisplay//__ANSI_CODE__/${StrAnsiCode}} ;
      StrLineDisplay=${StrLineDisplay//__COUNT__/${IntValue}} ;
     else 
      StrLineDisplay=${StrDisplayText};
      StrLineDisplay=${StrLineDisplay//__TEXT__/${StrStringSample}} ; 
      StrLineDisplay=${StrLineDisplay//__RESET__/${StrAnsiResetCode}} ; 
      StrLineDisplay=${StrLineDisplay//__ANSI_CODE__/${StrAnsiCode}} ;
      StrLineDisplay=${StrLineDisplay//__COUNT__/${IntValue}} ;
     fi

     echo -ne "${StrLineDisplay}\n" > ${StrErrDev} ; 
   else
    eval $( VTVIsArrayStyleInsert=True \
        VTVValueEntry=${StrVarList}   \
        VTVIsValueReAssign=True       \
        VTVIsValueToConvert=False     \
        VTVIsArrayStyleInsert=True    \
        ValueToVariable ) LoopDisplay ; 
   fi 
 }
	
 ###local StrSwitchMessages="Following switch are available:\n\n\t--startservices\tStart the application normally.\n\t--get\t\tReturn value of Internal Variable.\n\t--list\t\tList all Internal Pre-fixed Variable available to query or get.\n\n" ;
 local StrSwitchMessages="${StrSwitchesShow}${StrStartSwitches}\n${StrGetMsgSwitches}\n${StrListMsgSwitches}\n${StrCompWordMsgSwitches}\n" ;
 
 if [ "${Arg0:=--startservices}" == "--help"	] ; then 
  GetVarReference ${__call_locality[1]} ; 
  echo -ne "${StrSwitchMessages}" > ${StrErrDev} ; 
 elif [ "${Arg0:=--startservices}" == "--get" ] ; then 
  eval """local ArgGet=\${${ArrayArg[1]}}""" ; 
  echo -ne """${ArgGet}\n""" ;
 elif [ "${Arg0:=--startservices}" == "--list" ] ; then 
  eval $( __GetVarReferenceList ) ;
 elif [ "${Arg0:=--startservices}" == "--startservices" ] ; then 
  eval $( VTVIsArrayStyleInsert=True \
        VTVValueEntry=${StrVarList}   \
        VTVIsValueReAssign=True       \
        VTVIsValueToConvert=False     \
        VTVIsArrayStyleInsert=True    \
        ValueToVariable ) __main_StartServices
  IntStartRange=${IntStartRange}                 \
  IntEndRange=${IntEndRange}                     \
  StrAnsiResetCode=${StrAnsiResetCode}   \
  StrStringSample=${StrStringSample}       \
  __main_StartServices                                  ; 
 fi

}
