#!/bin/bash
###
### FootPrint Added, see Prefixed-Var ZSEAddFootPrint from ZenityShellEval
###

###File:/var/cache/Fnct.D/ZenityShellEval/877d7e9a-1001-11e3-98a2-001b3875b29c
###UUID-TIME-MARKER:0d10004c-9a32-11e6-8b1d-001e4c8856d6
###Date: 20161024-17:37:24,1477345044
###Sha1Sum: 12e054efa2622a76485ac08d50a1de89bcdf91e8
###Size:4742
###NbLine: 119
###NbWord: 397


unset FileNameConversion ;
function FileNameConversion()
{
   local __call_locality=( FNC FileNameConversion ) ;
   local ArrayArg=( $* ) ; 
   local Arg0=${ArrayArg[0]} ;
   local StrFileNameSearch=${FNCMimeTypeEntry:=tif} ;
   local StrFileNameReplace=${FNCMimeTypeConv:=pnm} ;
   local BoolRemoveFileExt=${FNCRemoveExt:=True} ;
   local StrTagList=${FNCTag:=__FILE__,__NEWFILE__,__ENTRY__,__CONV__,__PATH__} ;
   local StrTagAction=${FNCAppsConv:=/usr/bin/tifftopnm __PATH__/__FILE__.__ENTRY__ \> __PATH__/__NEWFILE__.__CONV__} ;
   local StrPath=${FNCPath:=./} ;
   local BoolDisplayCmd=${FNCDisplayCmd:=False} ;
   local StrFileListPrint=${FNCFindPrintf:="%f "} ;
   local StrFileListName=${FNCFindIname:=*.\${StrFileNameSearch}} ;
   local StrFileListFunc=${FNCFLFunc:=_FileList} ;

  function __LoopAction()
 {
   local __call_locality=( _LA __LoopAction ) ;
   local ArrayArg=( $* ) ; 
   local Arg0=${ArrayArg[0]} ;
   local BoolRemoveFileExt=${_LAIsRemoveext:=True} ;
   eval $( BVTestVarName=StrItem \
         BVTestVarHold='${Item//${StrFileNameSearch}/}' \
         BVTestBoolVarName=\${BoolRemoveFileExt}
         BVTestBoolCase=False \
         BVTestBoolAssertion='${Item}' BVTestScopeTest=local BoolVarTestVarCreation ) ; 
   local StrCmdEval=${StrTagAction} ; 
   local ArrayTagList=( ${StrTagList//,/ } ) ; 
   local ArrayVarValue=( ${StrItem} ${StrItem} ${StrFileNameSearch} ${StrFileNameReplace} ${StrPath} ) ;
   for (( intAx=0 ; intAx <= ${#ArrayTagList[@]}-1 ; intAx++ )) ; do
    local Tag=${ArrayTagList[${intAx}]} ; 
    local Value=${ArrayVarValue[${intAx}]} ; 
    StrCmdEval=${StrCmdEval//${Tag}/${Value}} ; 
   done
   function SubEvalDisplay()
   {
     echo -ne "CmdEval: ${StrCmdEval}\n" > /dev/stderr ; 
   }
   eval $( BVTestVarName=StrCmdDisplay \
               BVTestVarHold='$( StrCmdEval=${StrCmdEval} SubEvalDisplay )' \
               BVTestBoolVarName=\${BoolDisplayCmd}
               BVTestBoolCase=True \
               BVTestBoolAssertion='eval ${StrCmdEval}' BVTestScopeTest=local BoolVarTestVarCreation ) ; 
 }

 function _FileList()
 {
   local __call_locality=( _FL _FileList ) ;
   local ArrayArg=( $* ) ; 
   local Arg0=${ArrayArg[0]} ;
   eval local StrSearchReg="${StrFileListName}" ; 
   local StrCmdEval="find ${StrPath} -type f -iname \"${StrSearchReg}\" -printf \"${StrFileListPrint}\"" ;
   local StrReturn=$( eval "${StrCmdEval}" ) ; 
   echo -ne "${StrReturn}" ; 
 }

 function __main_StartServices()
 {
   local __call_locality=( Main __main_StartServices ) ;
   local ArrayArg=( $* ) ; 
   local Arg0=${ArrayArg[0]} ;
   #echo -ne "\n\tEntry in Function ${__call_locality[1]}\nVar StrTagList:${StrTagList}\n" > /dev/stderr ; 
   local StrEval=$( StrPath=${StrPath} \
                             StrFileNameSearch=${StrFileNameSearch} \
                             StrFileListPrint=${StrFileListPrint} \
                             ${StrFileListFunc} ) ; 
   local ArrayFile=( ${StrEval} ) ;
   #echo -ne "\n\tNbFile: ${#ArrayFile[@]}\n" > /dev/stderr  ; 
   for (( intx=0 ; intx <= ${#ArrayFile[@]}-1 ; intx++  )) ; do 
    local Item=${ArrayFile[${intx}]//.${StrFileNameSearch}/} ; 
    StrFileNameSearch=${StrFileNameSearch} \
    StrFileNameReplace=${StrFileNameReplace} \
    StrPath=${StrPath} Item=${Item} \
    BoolRemoveFileExt=${BoolRemoveFileExt} \
    StrTagAction=${StrTagAction} \
    StrTagList=${StrTagList} \
    StrNewFile=${StrNewFile} \
    BoolDisplayCmd=${BoolDisplayCmd} \
    StrFileListName=${StrFileListName} \
    StrFileListFunc=${StrFileListFunc} \
    __LoopAction ;
   done 
  
 }
 local StrSwitchMessages="Following switch are available:\n\n\t--startservices\tStart the application normally.\n\t--get\t\tReturn value of Internal Variable.\n\t--list\t\tList all Internal Pre-fixed Variable available to query or get.\n\n" ;
 if [ "${Arg0:=--startservices}" == "--help"	] ; then 
  GetVarReference ${__call_locality[1]} ; 
  echo -ne "${StrSwitchMessages}" > /dev/stderr ; 
 elif [ "${Arg0:=--startservices}" == "--get" ] ; then 
  eval """local ArgGet=\${${ArrayArg[1]}}""" ; 
  echo -ne """${ArgGet}\n""" ;
 elif [ "${Arg0:=--startservices}" == "--list" ] ; then 
  eval $( __GetVarReferenceList ) ;
 elif [ "${Arg0:=--startservices}" == "--startservices" ] ; then 
  StrFileNameSearch=${StrFileNameSearch} \
  StrFileNameReplace=${StrFileNameReplace} \
  StrPath=${StrPath} \
  BoolRemoveFileExt=${BoolRemoveFileExt} \
  StrTagAction=${StrTagAction} \
  StrTagList=${StrTagList} \
  StrNewFile=${StrNewFile} \
  BoolDisplayCmd=${BoolDisplayCmd} \
  __main_StartServices ; 
 fi
 
}

function test_FileNameConversion()
{
  FNCPath=/home/maxiste/Pictures/logo/out \
  FNCMimeTypeEntry=tif \
  FNCMimeTypeConv=pnm \
  FileNameConversion ; 
}
